### ISSUE TITLE
Contribute Helpful and Awesome Resources

### ISSUE THREAD

**Issue by lauragift21** [lauragift21/awesome-learning-resources#57]
As part of the [#Hacktoberfest](https://hacktoberfest.digitalocean.com) season I'll appreciate contributions from the community to this repository.

Check out the [Contributing Guide](https://github.com/lauragift21/awesome-learning-resources/blob/master/CONTRIBUTING.md) for instructions on how to make a contribution.

Happy Hacking!

**Comment by mai-am** [comment]
@lauragift21 Hi! I've made a branch where I'm adding some C# resources but I'm struggling a bit with making the table of contents link work since C# has the symbol hash in the name. I've tried using / before the # but it doesn't seem to want to link regardless. Do you have any experience with this? If you feel like testing feel free to make a table of contents entry for C# and then I can add the links I found in the body. I can just scrap my current commits in my branch if you manage.
